source 'https://rubygems.org'

ruby File.read(File.expand_path('../.ruby-version', __FILE__)).strip.sub(/ruby\-/, '')

gem 'rake', '~> 11.3'
gem 'httparty', '~> 0.14.0'
gem 'influxdb', '~> 0.3.12'

gem 'awesome_print'
